### ISSUE TITLE
UX problem in the address and card selection dialog

### ISSUE THREAD

**Issue by it-ony** [it-ony/payment-request#4]
If the user hasn't have chosen an address yet, a click on the address in the address selection dialog selects the address and also adds a little checkmark next to it. 

But if the user decides to change the address a click on the address doesn't select the address and bring back the user to the previous screen. The only way of going back is the little arrow on the top left.

The same is true for the credit card details, were I personally clicked on the button below the form to kind of confirm my selection. The problem here is that the button is not confirming the selection, but cancels the payment at all.

![creditcarddialog](https://user-images.githubusercontent.com/1348987/28723736-fb4f0212-73b7-11e7-9181-2915df1554c6.jpg)

**Comment by zkoch** [comment]
Thanks for this. Great feedback. Some good news is that we're changing the behavior so that if you click on an already selected address, we're going to "re-select" it and take you back to the main sheet (so no need to hit the back arrow).

**Comment by it-ony** [comment]
+1
