### ISSUE TITLE
Dev Tools debugger cannot be used, if payment UI is shown

### ISSUE THREAD

**Issue by it-ony** [it-ony/payment-request#5]
If the payment UI is shown, you cannot use the debugger in the dev tools, as the UI is acting like a modal dialog. 

Only way to help yourself out is to press `ESC`, which closes the UI and continue debugging, if you're already on a breakpoint or `debugger` statement. The problem here is, that even if you can continue debugging, the paymentRequest itself will be canceled.

![click into the source code](https://user-images.githubusercontent.com/1348987/28748175-34d13d6c-74b1-11e7-9bfd-6378aa316c9c.gif)

**Comment by rsolomakhin** [comment]
Can you try detaching the debugger into its own window?

**Comment by it-ony** [comment]
@rsolomakhin, that works.
